<?php

declare(strict_types=1);

function smtpProviderDefaults(string $provider): array
{
    return match (strtolower($provider)) {
        'gmail' => ['host'=>'smtp.gmail.com','port'=>587,'encryption'=>'tls'],
        'zoho' => ['host'=>'smtp.zoho.com','port'=>587,'encryption'=>'tls'],
        'custom' => ['host'=>'','port'=>587,'encryption'=>'tls'],
        default => ['host'=>'','port'=>587,'encryption'=>'tls'],
    };
}
function activeMailProvider(): string { $provider=strtolower(trim(getSetting('active_email_provider','none'))); return in_array($provider,['gmail','zoho','custom'],true)?$provider:'none'; }
function getMailConfig(?string $provider=null): array { $provider=$provider===null?activeMailProvider():strtolower(trim($provider)); if(!in_array($provider,['gmail','zoho','custom'],true)) return ['provider'=>'none','enabled'=>false,'validated'=>false]; $d=smtpProviderDefaults($provider); $p=$provider.'_smtp_'; return ['provider'=>$provider,'enabled'=>getSetting('email_service_enabled','0')==='1','validated'=>getSetting('email_smtp_validated','0')==='1','host'=>trim(getSetting($p.'host',(string)$d['host'])),'port'=>(int)getSetting($p.'port',(string)$d['port']),'encryption'=>strtolower(trim(getSetting($p.'encryption',(string)$d['encryption']))),'username'=>trim(getSetting($p.'username','')),'password'=>getSetting($p.'password',''),'from_email'=>trim(getSetting($p.'from_email','')),'from_name'=>trim(getSetting($p.'from_name','Gadget 50'))]; }
function emailServiceAvailable(): bool { $c=getMailConfig(); return $c['provider']!=='none'&&$c['enabled']&&$c['validated']&&$c['host']!==''&&$c['username']!==''&&$c['password']!==''&&filter_var($c['from_email'],FILTER_VALIDATE_EMAIL)!==false; }
function smtpRead($s,array $codes): void { $response=''; while(($line=fgets($s,515))!==false){$response.=$line;if(isset($line[3])&&$line[3]===' ')break;} $code=(int)substr($response,0,3);if(!in_array($code,$codes,true))throw new RuntimeException('SMTP server returned '.$code); }
function smtpWrite($s,string $command,array $codes): void { fwrite($s,$command."\r\n");smtpRead($s,$codes); }
function smtpSend(string $to,string $subject,string $body,array $c): bool { if(!filter_var($to,FILTER_VALIDATE_EMAIL)||$c['host']===''||$c['username']===''||$c['password']===''||!filter_var($c['from_email'],FILTER_VALIDATE_EMAIL))return false; $host=$c['encryption']==='ssl'?'ssl://'.$c['host']:$c['host'];$s=@stream_socket_client($host.':'.(int)$c['port'],$errno,$error,15,STREAM_CLIENT_CONNECT);if(!$s)return false;stream_set_timeout($s,15);try{smtpRead($s,[220]);smtpWrite($s,'EHLO gadget50.local',[250]);if($c['encryption']==='tls'){smtpWrite($s,'STARTTLS',[220]);if(!stream_socket_enable_crypto($s,true,STREAM_CRYPTO_METHOD_TLS_CLIENT))throw new RuntimeException('TLS failed');smtpWrite($s,'EHLO gadget50.local',[250]);}smtpWrite($s,'AUTH LOGIN',[334]);smtpWrite($s,base64_encode($c['username']),[334]);smtpWrite($s,base64_encode($c['password']),[235]);smtpWrite($s,'MAIL FROM:<'.$c['from_email'].'>',[250]);smtpWrite($s,'RCPT TO:<'.$to.'>',[250,251]);smtpWrite($s,'DATA',[354]);$name=$c['from_name']!==''?$c['from_name']:'Gadget 50';$headers='From: '.mb_encode_mimeheader($name,'UTF-8').' <'.$c['from_email'].'>\r\nTo: <'.$to.'>\r\nSubject: '.mb_encode_mimeheader($subject,'UTF-8').'\r\nMIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\n';fwrite($s,$headers."\r\n".$body."\r\n.\r\n");smtpRead($s,[250]);fwrite($s,"QUIT\r\n");return true;}catch(Throwable $e){error_log('SMTP error: '.$e->getMessage());return false;}finally{fclose($s);}}
function testSmtpConnection(array $c): bool { $c['enabled']=true;$c['validated']=true;return smtpSend($c['username'],'Gadget 50 SMTP test','<p>SMTP connection successful.</p>',$c); }
function sendEmail(string $to,string $subject,string $body): bool { return emailServiceAvailable()&&smtpSend($to,$subject,$body,getMailConfig()); }
function sendUserEmailVerification(array $user): bool { if(!emailServiceAvailable()||empty($user['email'])||getSetting('email_verification_enabled','0')!=='1')return false;$token=generateSecureToken();$pdo=Database::getInstance();$pdo->prepare('UPDATE users SET email_verification_token=:token,email_verification_expires_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 24 HOUR) WHERE id=:id')->execute([':token'=>$token,':id'=>(int)$user['id']]);return sendEmail((string)$user['email'],'Verify your email','<p><a href="'.e(appUrl('verify-email.php?token='.$token)).'">Verify your email</a></p>'); }
function sendPasswordResetEmail(array $user): bool { if(!emailServiceAvailable()||empty($user['email'])||getSetting('password_reset_email_enabled','0')!=='1')return false;$token=generateSecureToken();$pdo=Database::getInstance();$pdo->prepare('UPDATE users SET password_reset_token=:token,password_reset_expires_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 60 MINUTE) WHERE id=:id')->execute([':token'=>$token,':id'=>(int)$user['id']]);return sendEmail((string)$user['email'],'Reset your password','<p><a href="'.e(appUrl('reset-password.php?token='.$token)).'">Reset password</a></p>'); }
function sendAdminNewUserEmail(array $user): bool { $to=trim(getSetting('admin_alert_email',''));return $to===''||!emailServiceAvailable()?true:sendEmail($to,'New user registration','<p>Username: '.e((string)$user['username']).'</p>'); }
function sendTwoFactorCodeEmail(array $user,string $code): bool { return !empty($user['email'])&&sendEmail((string)$user['email'],'Your two-factor login code','<p>Code: <strong>'.e($code).'</strong></p>'); }
